/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminEditorsRouteImport } from './routes/admin/editors'
import { Route as AdminManuscriptsRouteImport } from './routes/admin/manuscripts'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorsRoute = AdminEditorsRouteImport.update({
  id: '/editors',
  path: '/editors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManuscriptsRoute = AdminManuscriptsRouteImport.update({
  id: '/manuscripts',
  path: '/manuscripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/manuscripts': typeof AdminManuscriptsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/admin': typeof AdminIndexRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/manuscripts': typeof AdminManuscriptsRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/editors': typeof AdminEditorsRoute
  '/admin/manuscripts': typeof AdminManuscriptsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/editor'
    | '/settings'
    | '/signup'
    | '/submit'
    | '/admin/editors'
    | '/admin/manuscripts'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/settings'
    | '/signup'
    | '/submit'
    | '/admin'
    | '/admin/editors'
    | '/admin/manuscripts'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/editor'
    | '/settings'
    | '/signup'
    | '/submit'
    | '/admin/_layout'
    | '/admin/editors'
    | '/admin/manuscripts'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editors': {
      id: '/admin/editors'
      path: '/editors'
      fullPath: '/admin/editors'
      preLoaderRoute: typeof AdminEditorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manuscripts': {
      id: '/admin/manuscripts'
      path: '/manuscripts'
      fullPath: '/admin/manuscripts'
      preLoaderRoute: typeof AdminManuscriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminEditorsRoute: typeof AdminEditorsRoute
  AdminManuscriptsRoute: typeof AdminManuscriptsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminEditorsRoute: AdminEditorsRoute,
  AdminManuscriptsRoute: AdminManuscriptsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
